version: "3.7"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false" # default is true, breaks health checks due to http # default is true, breaks health checks due to http
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:9200/_cat/health"]
      interval: 10s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - 5601:5601
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "http://localhost:5601/api/status"]
      interval: 10s
      timeout: 10s
      retries: 5
